open_graph:
  enable: true
  twitter_id: # for open_graph meta
article:
  type: tech # tech/story

logo:
  avatar: '[https://gitee.com/oymaster/img_beg/raw/master/setting/oy_icon.jpg](/about/)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
  subtitle: '加油' # '文字1 | 文字2' (鼠标放上去会切换到文字2)
